# Exercises on NumPy basics

These exercises use only the material covered in *Introduction to NumPy*.
Write your solution in the cell below each question, replacing `pass` or the comment.

In [2]:
import numpy as np

## Creating arrays and data types

1. A cantilever beam of length $L = 2$ m is discretised into $10$ equal intervals.

   1. Build the array `x` of the $11$ node coordinates with `np.linspace`, and print its `shape`, `size` and `dtype`.
   2. Build an array of the same length, filled with the constant cross-sectional area $A = 2.5\cdot10^{-3}$ m$^2$ (use `np.full`, then obtain the same result with `np.ones`), and an array of zeros of the same length, ready to hold the results. Print the `ndim` of these arrays.
   3. The beam is heated by $\Delta T = 60$ K. Compute the thermal displacement of every node, $u_i = \alpha \Delta T x_i$, with $\alpha = 1.2\cdot10^{-5}$ K$^{-1}$, and print the displacement of the free end in mm.
   4. Try to build the same grid with `np.arange(0., L, L/10)`: which node is missing, and why? This is the reason why `np.linspace` is preferred when the extremes matter.

In [20]:
L = 2.        # m
n_int = 10    # number of intervals

# Your code here
x=np.linspace(0,L,n_int)
A=np.full((n_int), 2.5e-3)
A2=np.ones(n_int)*2.5e-3
print(A.ndim, A2.ndim)

dT=60
alpha=1.2e-5
u=alpha*dT*x
print(u)


1 1
[0.      0.00016 0.00032 0.00048 0.00064 0.0008  0.00096 0.00112 0.00128
 0.00144]


2. Four strain gauges return their readings as floats, in strain units:

   ```python
   readings = np.array([1.2345e-3, 2.1017e-3, 0.9876e-3, 3.4562e-3])
   ```

   1. Convert them to microstrain ($1$ strain $= 10^6$ microstrain).
   2. Store the microstrains as integers with `astype(np.int64)`, and compare the result with the one obtained by rounding first (TIP: `np.round`). Which of the two is correct?
   3. Print the `dtype` before and after the conversion.
   4. Compute the maximum error introduced by the rounding, back in strain units.

In [16]:
readings = np.array([1.2345e-3, 2.1017e-3, 0.9876e-3, 3.4562e-3])

# Your code here
read=readings*1e6
read=np.round(read).astype(np.int64)
print(read.dtype)

print(f"The absoulte error is: {abs(readings*1e6-read)} microstrain")
print(np.max(np.abs(readings - read/1e6)))

int64
The absoulte error is: [0.5 0.3 0.4 0.2] microstrain
4.999999999998495e-07


## Indexing, slicing, views and copies

3. The results of a tensile test are collected in a table with one row per measurement and three columns, respectively strain $[-]$, stress $[$MPa$]$ and temperature $[^\circ$C$]$:

   ```python
   data = np.array([[0.000,   0., 20.0],
                    [0.001, 210., 21.2],
                    [0.002, 415., 23.4],
                    [0.003, 500., 26.1],
                    [0.004, 515., 30.5]])
   ```

   1. Extract the stress column and the strain column.
   2. Extract the first measurement (the whole row) and print its `shape` and its `ndim`. How does it differ from `data[0:1,:]`?
   3. Extract the sub-table of the strains and the stresses only (5 rows, 2 columns).
   4. Print the stress of the *last* measurement, using a negative index.
   5. The thermocouple was miscalibrated: add $0.5$ to the whole temperature column, writing directly into the table.

In [26]:
data = np.array([[0.000,   0., 20.0],
                 [0.001, 210., 21.2],
                 [0.002, 415., 23.4],
                 [0.003, 500., 26.1],
                 [0.004, 515., 30.5]])

# Your code here
strain=data[:,0]
stress=data[:,1]
m1=data[0,:]
print(np.shape(m1))
print(np.shape(data[0:1,:]))
print(np.ndim(m1))
print(np.ndim(data[0:1,:]))

subTable=data[:,:2]
print(subTable)

print(data[1,-1])
data[:,2]=data[:,2]+.5
print(data)

(3,)
(1, 3)
1
2
[[0.00e+00 0.00e+00]
 [1.00e-03 2.10e+02]
 [2.00e-03 4.15e+02]
 [3.00e-03 5.00e+02]
 [4.00e-03 5.15e+02]]
21.2
[[0.00e+00 0.00e+00 2.05e+01]
 [1.00e-03 2.10e+02 2.17e+01]
 [2.00e-03 4.15e+02 2.39e+01]
 [3.00e-03 5.00e+02 2.66e+01]
 [4.00e-03 5.15e+02 3.10e+01]]


4. Still on the table of the previous exercise:

   1. Build `stress = data[:,1]` and set its first element to $1000$. Look at `data`: what happened, and why?
   2. Restore the original value, then repeat the experiment on an independent copy of the column and verify that `data` is left untouched.
   3. Write a function `scaled_stress(table, factor)` that returns the stress column multiplied by `factor` **without** modifying the table it receives, and check it on `data`.

In [ ]:
# Your code here
stress = data[:,1]
stress[0]=1000
print(data[:,1])

stress[0]=0
print(data[:,1])
stress_copy=data[:,1].copy()
stress_copy[0]=1000.
print(data[:,1])

def scaled_stress(table,factor, stress_column):
    tc=table.copy()
    tc[:,stress_column]=tc[:,stress_column]*factor
    return tc

print(scaled_stress(data,2,1))
print(data)

[1000.  210.  415.  500.  515.]
[  0. 210. 415. 500. 515.]
[  0. 210. 415. 500. 515.]
[[0.00e+00 0.00e+00 2.05e+01]
 [1.00e-03 4.20e+02 2.17e+01]
 [2.00e-03 8.30e+02 2.39e+01]
 [3.00e-03 1.00e+03 2.66e+01]
 [4.00e-03 1.03e+03 3.10e+01]]
[[0.00e+00 0.00e+00 2.05e+01]
 [1.00e-03 2.10e+02 2.17e+01]
 [2.00e-03 4.15e+02 2.39e+01]
 [3.00e-03 5.00e+02 2.66e+01]
 [4.00e-03 5.15e+02 3.10e+01]]


## Element-wise operations

5. For a plane stress state with principal stresses $\sigma_1$ and $\sigma_2$, the von Mises equivalent stress is
   $$\sigma_{eq} = \sqrt{\sigma_1^2 - \sigma_1\sigma_2 + \sigma_2^2}.$$
   Four points of a component are characterised by

   ```python
   s1 = np.array([120., -80., 200.,  50.])   # MPa
   s2 = np.array([ 40., -150., -60.,  50.])  # MPa
   ```

   1. Compute the array of the equivalent stresses with a single vectorized expression (no loops).
   2. The material yields at $\sigma_y = 250$ MPa: compute the safety factor $\sigma_y/\sigma_{eq}$ of each point.
   3. Print the safety factors rounded to $2$ decimals (TIP: `np.round`).
   4. Verify that the fourth point, for which $\sigma_1 = \sigma_2$, has $\sigma_{eq} = \sigma_1$ (use `np.isclose`).

In [9]:
s1 = np.array([120., -80., 200.,  50.])   # MPa
s2 = np.array([ 40., -150., -60.,  50.])  # MPa

# Your code here
s_eq=np.sqrt(s1**2-s1*s2+s2**2)
print(s_eq)
sy=250
sf=sy/s_eq
print(f"Safety factor= {np.round(sf,2)}")

print(np.isclose(s1[3],s2[3]))
print(np.isclose(s1[3],s_eq[3]))

[105.83005244 130.         235.79652245  50.        ]
Safety factor= [2.36 1.92 1.06 5.  ]
True
True


6. The free vibration of a damped single-degree-of-freedom system has amplitude
   $$A(t) = A_0 e^{-\zeta \omega_n t},$$
   with $A_0 = 5$ mm, $\zeta = 0.05$ and $\omega_n = 2\pi\cdot 20$ rad/s.

   1. Build an array of $6$ instants between $0$ and $0.5$ s and compute the corresponding amplitudes with `np.exp`.
   2. Taking the logarithm of the amplitudes (`np.log`), verify that they decay linearly in time: the successive differences of $\log A$ must all be equal (use `np.allclose`).
   3. Recover the damping ratio $\zeta$ from the slope of $\log A$ and check that it matches the value used to generate the data.

In [16]:
A0 = 5.               # mm
zeta = 0.05
omega_n = 2*np.pi*20  # rad/s

# Your code here
t=np.linspace(0,0.5,6)
At=A0*np.exp(-zeta*omega_n*t)

logAt=np.log(At)
print(np.isclose(logAt[0]-logAt[1],logAt[1]-logAt[2]))

slope=(logAt[1]-logAt[0])/(t[1]-t[0])
print(np.isclose(-slope/omega_n,zeta))

True
True


7. Eight bolt holes are drilled on a flange. Their Cartesian coordinates, in mm, are built by the code below.

   1. Extract the $x$ and $y$ columns and convert the positions to polar coordinates, i.e. compute the radius $r=\sqrt{x^2+y^2}$ and the angle of each hole. TIP: use `np.arctan2(y, x)`, which returns the angle in the correct quadrant (see the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html)), and convert it to degrees with `np.degrees`.
   2. Verify with `np.allclose` that all the holes lie on the same circle, and print its radius.
   3. Print the angular pitch between two consecutive holes.

In [21]:
theta = np.linspace(0., 2*np.pi, 8, endpoint=False)
holes = np.hstack((60*np.cos(theta).reshape(-1,1), 60*np.sin(theta).reshape(-1,1)))
print(holes)

# Your code here
x=holes[:,0]
y=holes[:,1]
r=np.sqrt(x**2+y**2)
print(r)
rad=np.arctan2(y,x)
print(np.degrees(rad))


[[ 6.00000000e+01  0.00000000e+00]
 [ 4.24264069e+01  4.24264069e+01]
 [ 3.67394040e-15  6.00000000e+01]
 [-4.24264069e+01  4.24264069e+01]
 [-6.00000000e+01  7.34788079e-15]
 [-4.24264069e+01 -4.24264069e+01]
 [-1.10218212e-14 -6.00000000e+01]
 [ 4.24264069e+01 -4.24264069e+01]]
[60. 60. 60. 60. 60. 60. 60. 60.]
[   0.   45.   90.  135.  180. -135.  -90.  -45.]


## Comparisons, masks and filtering

8. A batch of $200$ shafts is measured at the end of the production line. The nominal diameter is $5.00$ mm and the tolerance band is $\pm 0.03$ mm.

   1. Build the mask of the pieces *within* tolerance, and the mask of the rejected ones.
   2. How many pieces are rejected? Which percentage of the batch is it (1 decimal)?
   3. Is there at least one piece above $5.05$ mm? Are all the pieces above $4.90$ mm? (`np.any`, `np.all`)
   4. Print the diameters of the rejected pieces and the largest deviation from the nominal value, in micrometres.

In [ ]:
rng = np.random.default_rng(seed=3)
diameters = rng.normal(5.0, 0.02, 200)   # mm

# Your code here
tol=0.03
mask=(5-tol <= diameters) & (diameters <= 5+tol)
rejected=diameters.size-sum(mask)
print(f"rejected pieces: {rejected}, {(rejected/diameters.size):.1%}")

print(f"pieces above 5.05 mm: {np.any(diameters > 5.05)}, all pieces above 4.90mm: {np.all(diameters > 4.9)}")
rej=~mask
print(diameters[rej])
print(f"max deviation: {1000*max(abs(5-diameters))} micrometers")


rejected pieces: 30, 15.0%
pieces above 5.05 mm: True, all pieces above 4.90mm: True
[5.04081838 4.9488867  4.95960028 5.06645999 5.03091642 5.03870176
 4.94343675 4.9666276  4.95012211 4.96722286 4.95931665 4.95683989
 5.0318128  4.9656363  5.03363651 4.96539973 5.05100069 4.95920992
 4.95441947 5.04095772 5.03519853 5.03009895 5.04926264 4.96947682
 5.03390415 4.9581903  5.03219325 5.04321813 5.04351151 5.03231364]
max deviation: 66.45999033289752micrometers


9. A data logger sampled the stress in a component once per second, writing $-999$ whenever the acquisition failed:

   ```python
   stress = np.array([120., 135., -999., 150., 168., -999., 210., 260., 245.])   # MPa
   ```

   1. Build the mask of the valid samples and compute their mean.
   2. Using `np.where`, build a *cleaned* array in which every invalid sample is replaced by the mean of the valid ones.
   3. The component yields at $250$ MPa. Using `np.where`, find the indices of the valid samples above the yield stress and print the first one, i.e. the instant at which the component yields (or $-1$ if it never happens).

In [62]:
stress = np.array([120., 135., -999., 150., 168., -999., 210., 260., 245.])   # MPa

# Your code here
valid=stress >-999
meanStress=sum(stress[valid])/sum(valid)
print(meanStress)
print(np.where(stress>-999,stress, meanStress))
idx=np.where(stress>250)[0]
print(idx)

if idx.size>0:
    print(stress[idx[0]])
else:
    print(-1)


184.0
[120. 135. 184. 150. 168. 184. 210. 260. 245.]
[7]
260.0


## Reductions and the axis argument

10. Three accelerometers monitor a gearbox. The table below contains one row per time step and one column per sensor (accelerations in $g$):

    ```python
    acc = np.array([[0.12, 0.31, 0.08],
                    [0.15, 0.29, 0.11],
                    [0.22, 0.35, 0.09],
                    [0.19, 0.41, 0.12],
                    [0.31, 0.38, 0.15],
                    [0.28, 0.44, 0.13]])
    ```

    1. Compute the mean, the standard deviation, the minimum and the maximum of each *sensor*.
    2. Compute the maximum acceleration recorded at each *time step*.
    3. Which sensor recorded the largest peak? (TIP: `argmax` on the maxima of each sensor.)
    4. At which time step did the overall maximum occur?
    5. Compute the RMS value of each sensor, $\sqrt{\overline{a^2}}$.

In [73]:
acc = np.array([[0.12, 0.31, 0.08],
                [0.15, 0.29, 0.11],
                [0.22, 0.35, 0.09],
                [0.19, 0.41, 0.12],
                [0.31, 0.38, 0.15],
                [0.28, 0.44, 0.13]])

# Your code here
print(acc.mean(axis=0))
print(acc.std(axis=0))
print(acc.min(axis=0))
print(acc.max(axis=0))

print(acc.max(axis=1))

sensormax=acc.max(axis=0)
print(acc.max(axis=0).argmax(axis=0))
print(acc.max(axis=1).argmax(axis=0))

print(np.sqrt((acc**2).mean(axis=0)))

[0.21166667 0.36333333 0.11333333]
[0.06718548 0.05280993 0.02357023]
[0.12 0.29 0.08]
[0.31 0.44 0.15]
[0.31 0.29 0.35 0.41 0.38 0.44]
1
5
[0.22207356 0.3671512  0.11575837]


## Broadcasting

11. The nodes of a plane truss have coordinates (in m)

    ```python
    nodes = np.array([[0., 0.],
                      [1., 0.],
                      [2., 0.],
                      [1., 1.]])
    ```

    1. Build the $4\times4$ matrix `D` of the distances between every pair of nodes, **without loops**. TIP: `nodes[:,np.newaxis,:]` has shape $(4,1,2)$ and `nodes[np.newaxis,:,:]` has shape $(1,4,2)$, so their difference has shape $(4,4,2)$; then sum the squares along the last axis.
    2. Check with `np.allclose` that `D` is symmetric and that its diagonal is zero (TIP: `np.diag(D)` extracts the diagonal of a matrix).
    3. Print the largest distance between two nodes and the mean distance of node $0$ from the other nodes.

    BONUS. Write a function that, given two arrays $x$ and $y$ of length $n$ and $m$, returns the $n \times m$ *Cauchy matrix* $C_{ij} = 1/(x_i - y_j)$, again exploiting broadcasting.

In [89]:
nodes = np.array([[0., 0.],
                  [1., 0.],
                  [2., 0.],
                  [1., 1.]])

# Your code here
# print(nodes[:,np.newaxis,:])
# print(nodes[np.newaxis,:,:])
diff = nodes[:,np.newaxis,:] - nodes[np.newaxis,:,:]
D = np.sqrt((diff**2).sum(axis=2))
print(np.round(D, 3))

print(np.allclose(np.diag(D),0))
print(np.max(D))
print(D[0,1:].mean())

# BONUS: x becomes a column of shape (n,1), y stays a row of shape (m,)
def cauchy_matrix(x, y):
    return 1/(x.reshape((-1,1)) - y)

x = np.array([1., 2., 3.])
y = np.array([4., 5., 6., 7.])
print(cauchy_matrix(x, y).shape)
print(cauchy_matrix(x, y))


[[0.    1.    2.    1.414]
 [1.    0.    1.    1.   ]
 [2.    1.    0.    1.414]
 [1.414 1.    1.414 0.   ]]
True
2.0
1.4714045207910316
(3, 4)
[[-0.33333333 -0.25       -0.2        -0.16666667]
 [-0.5        -0.33333333 -0.25       -0.2       ]
 [-1.         -0.5        -0.33333333 -0.25      ]]


## Shape manipulation and concatenation

12. A test rig sampled the displacement of a shaker table, $u(t) = 0.05\sin(2\pi\,5\,t)$ m.

    1. Build `t` with $5$ points between $0$ and $0.2$ s (one period of the signal), compute `u`, then assemble the $5\times2$ table whose columns are `t` and `u` (TIP: `reshape` both into columns, then `np.hstack`).
    2. A second experiment produced the same table: stack the two one below the other with `np.vstack` and print the shape of the result.
    3. Flatten the table into a one-dimensional array with `ravel()` and print its shape.
    4. Print the transpose of the table and its shape, using both `.T` and `np.transpose`.
    5. Rebuild the table of point 1 with `np.concatenate`, choosing the right `axis`, and check the result with `np.allclose`.

    BONUS. Create two $2\times2$ matrices of random integers between $1$ and $4$, concatenate them horizontally and multiply the result by a random $4\times2$ matrix.

In [ ]:
# Your code here
t=np.linspace(0,0.2,5)
u=0.05*np.sin(2*np.pi*5*t)
t=t.reshape(5,1)
u=u.reshape(5,1)
table=np.hstack((t,u))
print(table.shape)

table2=np.vstack((table,table))
print(table2.shape)

arr=table.ravel()
print(arr.shape)

print(table.T.shape)
print(np.transpose(table).shape)
same=np.concatenate((t,u),axis=1)
print(np.allclose(same,table))




(5, 2)
(10, 2)
(10,)
(2, 5)
(2, 5)
True


## Sorting, searching and unique values

13. Write a function that, given an array `a` and a positive integer $n$, returns the $n$ largest elements of `a`, ordered from the largest downwards. Apply it to the peak loads (in kN) recorded during a test campaign:

    ```python
    loads = np.array([1., 4., 2., 4.3, 5., 12., 7., 8., 2.])   # kN
    ```

    Expected output for $n = 5$: `[12., 8., 7., 5., 4.3]`

In [117]:
loads = np.array([1., 4., 2., 4.3, 5., 12., 7., 8., 2.])   # kN
def get_largest(a, n):
    # n must be strictly positive
    assert n > 0
    return np.sort(a)[::-1][:n]

print(get_largest(loads,5))


[12.   8.   7.   5.   4.3]


14. Six candidate materials are described by their density and their yield strength:

    ```python
    names = np.array(["steel", "aluminium", "titanium", "copper", "magnesium", "CFRP"])
    density = np.array([7850., 2700., 4500., 8960., 1740., 1600.])    # kg/m^3
    strength = np.array([355., 270., 880., 210., 200., 600.])         # MPa
    ```

    1. Compute the *specific strength* (strength divided by density) of each material.
    2. Using `np.argsort`, print the three best materials for a lightweight design, from the best downwards, together with their specific strength.
    3. Print the name of the material with the smallest specific strength, using `argmin`.

In [130]:
names = np.array(["steel", "aluminium", "titanium", "copper", "magnesium", "CFRP"])
density = np.array([7850., 2700., 4500., 8960., 1740., 1600.])    # kg/m^3
strength = np.array([355., 270., 880., 210., 200., 600.])         # MPa

# Your code here
ss=strength/density
print(np.round(ss,4))
print(names[np.argsort(ss)][::-1][:3])
print(names[np.argmin(ss)])

[0.0452 0.1    0.1956 0.0234 0.1149 0.375 ]
['CFRP' 'titanium' 'magnesium']
copper


15. During a fatigue campaign, every test is logged as a row `[load level, frequency]`. The same combination may have been repeated several times:

    ```python
    tests = np.array([[100., 10.],
                      [150., 10.],
                      [100., 10.],
                      [150., 20.],
                      [100., 10.]])
    ```

    Using `np.unique`, write a function that returns the distinct rows of a two-dimensional array, and apply it to `tests` to obtain the list of the distinct test conditions. How many of them are there?

In [133]:
def unique_rows(A):
    return np.unique(A, axis=0)

tests = np.array([[100., 10.],
                  [150., 10.],
                  [100., 10.],
                  [150., 20.],
                  [100., 10.]])

print(unique_rows(tests).shape[0])

3


16. Two small searching utilities.

    1. Write a function that, given an *integer* array `x` and an *integer* `y`, returns the index of the first occurrence of `y` in `x`, or $-1$ if `y` does not appear. TIP: `np.where`.

       Example: `x = [1,2,4,21,5,2,3]`, `y = 2` gives `index = 1`.

    2. Write a function that, given an array of floats and a float, returns the element of the array closest to that number. TIP: `np.abs` and `argmin`. Apply it to find, in the catalogue of standard bar diameters `[6., 8., 10., 12., 16., 20., 25., 32.]` mm, the one closest to a computed diameter of $13.7$ mm.

In [140]:
def first_occurrence(x, y):
    occur = np.where(y==x)[0]
    return occur[0] if occur.size > 0 else -1

def closest_element(array, number):
    return Dbar[np.argmin(np.abs(Dbar-num))]

x = np.array([1, 2, 4, 21, 5, 2, 3])
print(first_occurrence(x, 2))
print(first_occurrence(x, 7))

Dbar=np.array([6., 8., 10., 12., 16., 20., 25., 32.])
num=13.7
print(closest_element(Dbar,num))


1
-1
12.0


## Linear algebra

17. Three masses are connected by springs to a wall and to each other. Under the static loads $f$, their displacements $u$ solve the linear system $K u = f$, with

    ```python
    K = 1e3*np.array([[200., -100.,    0.],
                      [-100.,  200., -100.],
                      [   0., -100.,  100.]])   # N/m
    f = np.array([0., 0., 500.])                # N
    ```

    1. Solve the system with `np.linalg.solve` and print the displacements in mm.
    2. Verify the solution: check with `np.allclose` that $Ku = f$ (the product can be written `K @ u` or `np.dot(K, u)`), and print the norm of the residual $\|Ku-f\|$ with `np.linalg.norm`.
    3. Check that $K$ is symmetric, comparing it with its transpose.
    4. Compute $K^{-1}$ and verify that $K K^{-1}$ is the identity matrix (`np.eye`). Note that solving the system directly is preferable to inverting the matrix.

    BONUS. If the three masses are unitary, the natural angular frequencies of the system are $\omega_j = \sqrt{\lambda_j}$, where $\lambda_j$ are the eigenvalues of $K$. Compute them with `np.linalg.eigh` and print the corresponding frequencies $f_j = \omega_j/(2\pi)$ in Hz.

In [151]:
K = 1e3*np.array([[200., -100.,    0.],
                  [-100.,  200., -100.],
                  [   0., -100.,  100.]])   # N/m
f = np.array([0., 0., 500.])                # N

# Your code here
u=np.linalg.solve(K,f)
print(u)
print(np.allclose(K @ u,f))
print(np.linalg.norm(K @ u - f))

print(np.allclose(K,K.T))

Kinv=np.linalg.inv(K)
print(np.allclose(K@Kinv,np.eye(3,3)))

eigval, eigvec=np.linalg.eigh(K)
freq=np.sqrt(eigval)/(2*np.pi)
print(freq)

[0.005 0.01  0.015]
True
7.866737095637891e-14
True
True
[22.39860657 62.75950097 90.6901065 ]


## Reading and writing arrays

18. Save the displacements computed in the previous exercise to the file `displacements.npy`, reload them into a different variable and check with `np.allclose` that nothing was lost. Do the same with the whole stiffness matrix.

In [ ]:
# Your code here
